### ISSUE TITLE
Izpisi v command line

### ISSUE THREAD

**Issue by zkokalj** [EarthObservation/Image-stacking#3]
Urejanje izpisov v comandline med samim računanjem in vnos začetnih parametrov (izbira primernaga kanala, ter slike v kanalu na katero prilagajamo druge)

**Comment by jurenemec** [comment]
Dodan je vnos paramatrov v cmd line:

channel_id
template_id
averaging_mode (opis v readme)
file_name(optional)

v cmd je tudi viden napredek posamezne faze postopka
