### ISSUE TITLE
Barve

### ISSUE THREAD

**Issue by zkokalj** [EarthObservation/Image-stacking#4]
odprava problema z barvami (verjetno do tega pride nekje med samim odpiranjem ali shranjevanjem z knjižnico GDAL)

**Comment by jurenemec** [comment]
Vrednosti barv so izračuanane pravilno. Pride pa do različnega prikaza če so na sliki kakšni ostanki črnega roba. Potem je naprimer razpon rdeče barve od 0 do 8400, če ga pa ni (črnega roba) pa je razpon od 4700 do 8400. Potem qgis drugače prikaže slike.

Rezultat:

![resulte](https://user-images.githubusercontent.com/48442391/54884554-db0fe100-4e72-11e9-868e-fdbbd7734d5e.png)
