### ISSUE TITLE
normalizacija

### ISSUE THREAD

**Issue by zkokalj** [EarthObservation/Image-stacking#5]
Pri sestavljanju posnetkov je treba upoštevati, koliko posnetkov pokriva določen piksel, da ne bodo vidni pasovi.

**Comment by jurenemec** [comment]
Odstranim samo še črna pasa po vertikali pa bo.


![result_image_gdalsave](https://user-images.githubusercontent.com/48442391/54585224-d209b480-4a19-11e9-8f64-1c82aacf89e7.jpg)

**Comment by jurenemec** [comment]
Odstranjen črni del.

![resulte](https://user-images.githubusercontent.com/48442391/54884535-9c7a2680-4e72-11e9-9996-68672ff83b37.png)

**Comment by jurenemec** [comment]
Povprečenje po celi sliki, v odvisnosti od števila slik, ki se prekrivajo.

![resulte](https://user-images.githubusercontent.com/48442391/55002123-56d66e80-4fd6-11e9-807b-7569f5ec8170.png)
